# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pagingMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pagingMenu
  pod 'SnapKit', '4.2.0'
  pod 'MJRefresh'
  pod 'Aquaman'
  pod 'BadgeSwift'
  #pod 'Trident'
end
